In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r'C:\Users\DELL\Downloads\youtube\INvideos.csv')

In [53]:
## To check data

In [54]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,NaT,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,"sharry mann|""sharry mann new song""|""sharry man...",0.109633,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,NaT,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13 05:43:56+00:00,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",0.059010,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं..."
2,10L1hZ9qa58,NaT,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12 15:48:08+00:00,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,0.047399,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,NaT,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12 07:08:48+00:00,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",0.124268,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,NaT,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13 01:14:16+00:00,"Filmylooks|""latest news""|""telugu movies""|""telu...",0.046401,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...

In [55]:
## To check rows and columns

In [5]:
df.shape

(37352, 16)

In [56]:
# to check null values

In [6]:
df.isnull().sum()

video_id                    0
trending_date               0
title                       0
channel_title               0
category_id                 0
publish_time                0
tags                        0
views                       0
likes                       0
dislikes                    0
comment_count               0
thumbnail_link              0
comments_disabled           0
ratings_disabled            0
video_error_or_removed      0
description               561
dtype: int64

In [57]:
## TO check data types

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37352 entries, 0 to 37351
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37352 non-null  object
 1   trending_date           37352 non-null  object
 2   title                   37352 non-null  object
 3   channel_title           37352 non-null  object
 4   category_id             37352 non-null  int64
 5   publish_time            37352 non-null  object
 6   tags                    37352 non-null  object
 7   views                   37352 non-null  int64
 8   likes                   37352 non-null  int64
 9   dislikes                37352 non-null  int64
 10  comment_count           37352 non-null  int64
 11  thumbnail_link          37352 non-null  object
 12  comments_disabled       37352 non-null  bool
 13  ratings_disabled        37352 non-null  bool
 14  video_error_or_removed  37352 non-null  bool
 15  description             36791 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 3.8+ MB

In [58]:
## to check statistics of data

In [8]:
df.describe()

        category_id         views         likes      dislikes  comment_count
count  37352.000000  3.735200e+04  3.735200e+04  3.735200e+04    37352.00000
mean      21.576596  1.060478e+06  2.708272e+04  1.665082e+03     2676.99743
std        6.556593  3.184932e+06  9.714510e+04  1.607617e+04    14868.31713
min        1.000000  4.024000e+03  0.000000e+00  0.000000e+00        0.00000
25%       23.000000  1.239155e+05  8.640000e+02  1.080000e+02       81.00000
50%       24.000000  3.045860e+05  3.069000e+03  3.260000e+02      329.00000
75%       24.000000  7.992912e+05  1.377425e+04  1.019250e+03     1285.00000
max       43.000000  1.254322e+08  2.912710e+06  1.545017e+06   827755.00000

In [9]:
df["category_id"]=df["category_id"].astype(str)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37352 entries, 0 to 37351
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37352 non-null  object
 1   trending_date           37352 non-null  object
 2   title                   37352 non-null  object
 3   channel_title           37352 non-null  object
 4   category_id             37352 non-null  object
 5   publish_time            37352 non-null  object
 6   tags                    37352 non-null  object
 7   views                   37352 non-null  int64
 8   likes                   37352 non-null  int64
 9   dislikes                37352 non-null  int64
 10  comment_count           37352 non-null  int64
 11  thumbnail_link          37352 non-null  object
 12  comments_disabled       37352 non-null  bool
 13  ratings_disabled        37352 non-null  bool
 14  video_error_or_removed  37352 non-null  bool
 15  description             36791 non-null  object
dtypes: bool(3), int64(4), object(9)
memory usage: 3.8+ MB

##### to change datatype to datetime

In [11]:
df["publish_time"] = pd.to_datetime(df["publish_time"])

In [12]:
df.head(10)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,17.14.11,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13 05:43:56+00:00,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं..."
2,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12 15:48:08+00:00,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12 07:08:48+00:00,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13 01:14:16+00:00,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...
5,il_pSa5l98w,17.14.11,"MCA (Middle Class Abbayi) TEASER - Nani,Sai Pa...",Dil Raju,24,2017-11-10 04:29:50+00:00,"Nenu Local|""Nenu Local Telugu Movie""|""Nani""|""S...",6106669,98612,4185,4763,https://i.ytimg.com/vi/il_pSa5l98w/default.jpg,False,False,False,Watch MCA- Middle Class Abbayi First Look Teas...
6,7MxiQ4v0EnE,17.14.11,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11 16:41:15+00:00,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,8063,https://i.ytimg.com/vi/7MxiQ4v0EnE/default.jpg,False,False,False,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...
7,c64I9HNpiOY,17.14.11,Padmavati : Ek Dil Ek Jaan Video Song | Deepik...,T-Series,10,2017-11-11 06:14:19+00:00,"Ek Dil Ek Jaan Video Song|""'Ek Dil Ek Jaan'""|""...",10588371,132738,8812,10847,https://i.ytimg.com/vi/c64I9HNpiOY/default.jpg,False,False,False,Presenting the song 'Ek Dil Ek Jaan' from Padm...
8,KObFEYCaRx8,17.14.11,Chiranjeevi in Naga Chaitanya - Samantha Recep...,Top Telugu Media,24,2017-11-13 04:42:26+00:00,Chiranjeevi in Naga Chaitanya - Samantha Recep...,118223,520,53,23,https://i.ytimg.com/vi/KObFEYCaRx8/default.jpg,False,False,False,Chiranjeevi in Naga Chaitanya - Samantha Recep...
9,g8QsfJhFpjY,17.14.11,New bike vs Old bike - the reality,Jump Cuts,24,2017-11-12 04:30:01+00:00,"Jump cuts|""Jumpcuts""|""Tamil comedy""|""Tamil Com...",969030,59798,1545,2404,https://i.ytimg.com/vi/g8QsfJhFpjY/default.jpg,False,False,False,Jump Cuts is a Tamil entertaining group by Har...

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37352 entries, 0 to 37351
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37352 non-null  object
 1   trending_date           37352 non-null  object
 2   title                   37352 non-null  object
 3   channel_title           37352 non-null  object
 4   category_id             37352 non-null  object
 5   publish_time            37352 non-null  datetime64[ns, UTC]
 6   tags                    37352 non-null  object
 7   views                   37352 non-null  int64
 8   likes                   37352 non-null  int64
 9   dislikes                37352 non-null  int64
 10  comment_count           37352 non-null  int64
 11  thumbnail_link          37352 non-null  object
 12  comments_disabled       37352 non-null  bool
 13  ratings_disabled        37352 non-null  bool
 14  video_error_or_removed  37352 non-null  bool
 15  description             36791 non-null  object
dtypes: bool(3), datetime64[ns, UTC](1), int64(4), object(8)
memory usage: 3.8+ MB

#### Converted views values in Cr

In [14]:
df["views"]=df["views"]/10000000

#### TO check which channel having more views

In [59]:
df1=df.groupby("channel_title",as_index=False)["views"].sum()

In [63]:
df1.sort_values("views",ascending=False)

             channel_title       views
1052              T-Series  212.460791
631   Marvel Entertainment  128.039620
356           FoxStarHindi  126.080762
78            Amit Bhadana  102.425217
1019         Speed Records   80.173941
...                    ...         ...
795                Pakkatv    0.001344
894           Reporter Roy    0.001182
1282        Viral in India    0.001139
1315   Wide Angle Pictures    0.001134
740             News VIdeo    0.000757

[1426 rows x 2 columns]

TO check average views of channels

In [61]:
df2=df.groupby("channel_title",as_index=False)["views"].mean()

In [62]:
df2.sort_values("views",ascending=False)

                    channel_title     views
1339            YouTube Spotlight  8.226435
1126              TaylorSwiftVEVO  2.864121
1013  Sony Pictures Entertainment  2.271359
356                  FoxStarHindi  2.251442
631          Marvel Entertainment  1.969840
...                           ...       ...
894                  Reporter Roy  0.001182
1282               Viral in India  0.001139
1315          Wide Angle Pictures  0.001134
768              OneVision Telugu  0.001033
740                    News VIdeo  0.000757

[1426 rows x 2 columns]

##### To check time period if data

In [68]:
df['trending_date'] = pd.to_datetime(df['trending_date'], errors='coerce')

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37352 entries, 0 to 37351
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37352 non-null  object
 1   trending_date           13867 non-null  datetime64[ns]
 2   title                   37352 non-null  object
 3   channel_title           37352 non-null  object
 4   category_id             37352 non-null  object
 5   publish_time            37352 non-null  datetime64[ns, UTC]
 6   tags                    37352 non-null  object
 7   views                   37352 non-null  float64
 8   likes                   37352 non-null  int64
 9   dislikes                37352 non-null  int64
 10  comment_count           37352 non-null  int64
 11  thumbnail_link          37352 non-null  object
 12  comments_disabled       37352 non-null  bool
 13  ratings_disabled        37352 non-null  bool
 14  video_error_or_removed  37352 non-null  bool
 15  description             36791 non-null  object
dtypes: bool(3), datetime64[ns, UTC](1), datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 3.8+ MB

In [70]:
print(df["trending_date"].min())
print(df["trending_date"].max())

2001-01-18 00:00:00
2012-12-17 00:00:00

In [71]:
df3=(df["channel_title"].unique())

In [72]:
df3.shape

(1426,)

In [73]:
(df[df.duplicated])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
1689,YAzs-timxnI,NaT,Swag Se Swagat Song | Official Teaser | Salman...,YRF,10,2017-11-20 08:40:48+00:00,"Salman Khan|""Katrina Kaif""|""Tiger Zinda Hai So...",0.279032,46228,5088,3807,https://i.ytimg.com/vi/YAzs-timxnI/default.jpg,False,False,False,► Subscribe Now: https://goo.gl/xs3mrY 🔔 Stay ...
1690,ZJDMWVZta3M,NaT,Incredibles 2 Official Teaser Trailer,Disney•Pixar,1,2017-11-18 15:43:11+00:00,"Pixar|""Disney""|""Disney Pixar""|""Pixar Movie""|""A...",1.761387,369519,7892,45240,https://i.ytimg.com/vi/ZJDMWVZta3M/default.jpg,False,False,False,The teaser trailer for Incredibles 2 is here.\...
1691,RVpnz8mbVDI,NaT,Jaisi Karni Waisi Bharni - | Lalit Shokeen Fil...,LShokeen Films,24,2017-11-20 14:27:43+00:00,"lalit shokeen|""lalit shokeen films""|""lalit sho...",0.073369,31866,883,2392,https://i.ytimg.com/vi/RVpnz8mbVDI/default.jpg,False,False,False,Jaisi karni waisi bharni - jyada oversmart ban...
1692,CfZSYm-mFgI,NaT,Bomma Adhirindhi Song Trailer | Jawaan Telugu ...,Arunachal Creations,22,2017-11-19 17:15:38+00:00,"Bomma Adhirindhi Song Trailer|""Jawaan Telugu M...",0.055026,3184,426,187,https://i.ytimg.com/vi/CfZSYm-mFgI/default.jpg,False,False,False,Bomma Adhirindhi Song Trailer from Jawaan Telu...
1693,m1PDqdLQMv8,NaT,Miss World 2017 Top 5 Question and Answer,Beauty Pageants,24,2017-11-18 15:02:47+00:00,"miss world 2017|""manushi chhillar""|""manushi ch...",0.750292,68262,3337,539,https://i.ytimg.com/vi/m1PDqdLQMv8/default.jpg,False,False,False,Watch the Top 5 question and answer at the Mis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37347,iNHecA3PJCo,NaT,फेकू आशिक़ - राजस्थान की सबसे शानदार कॉमेडी | ...,RDC Rajasthani,23,2018-06-13 08:01:11+00:00,"twinkle vaishnav comedy|""twinkle vaishnav""|""tw...",0.021438,3291,404,196,https://i.ytimg.com/vi/iNHecA3PJCo/default.jpg,False,False,False,PRG Music & RDC Rajasthani presents फेकू आशिक़...
37348,dpPmPbhcslM,NaT,Seetha | Flowers | Ep# 364,Flowers TV,24,2018-06-13 11:30:04+00:00,"flowers serials|""actress""|""malayalam serials""|...",0.040683,1726,478,1428,https://i.ytimg.com/vi/dpPmPbhcslM/default.jpg,False,False,False,"Flowers - A R Rahman Show,Book your Tickets He..."
37349,mV6aztP58f8,NaT,Bhramanam I Episode 87 - 12 June 2018 I Mazhav...,Mazhavil Manorama,24,2018-06-13 05:00:02+00:00,"mazhavil manorama|""bhramanam full episode""|""gt...",0.038632,1216,453,697,https://i.ytimg.com/vi/mV6aztP58f8/default.jpg,False,False,False,Subscribe to Mazhavil Manorama now for your da...
37350,qxqDNP1bDEw,NaT,Nua Bohu | Full Ep 285 | 13th June 2018 | Odia...,Tarang TV,24,2018-06-13 15:07:49+00:00,"tarang|""tarang tv""|""tarang tv online""|""tarang ...",0.013026,698,115,65,https://i.ytimg.com/vi/qxqDNP1bDEw/default.jpg,False,False,False,Nuabohu : Story of a rustic village girl who w...
37351,wERgpPK44w0,NaT,Ee Nagaraniki Emaindi Trailer | Tharun Bhascke...,Suresh Productions,24,2018-06-10 04:29:54+00:00,"Ee Nagaraniki Emaindi|""Ee Nagaraniki Emaindi T...",0.127825,22466,1609,1205,https://i.ytimg.com/vi/wERgpPK44w0/default.jpg,False,False,False,Check out Ee Nagaraniki Emaindi Trailer #EeNag...

In [74]:
print("Shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nData types:\n", df.dtypes)
print("\nSample values:\n", df.head())

Shape: (37352, 16)

Missing values:
 video_id                      0
trending_date             23485
title                         0
channel_title                 0
category_id                   0
publish_time                  0
tags                          0
views                         0
likes                         0
dislikes                      0
comment_count                 0
thumbnail_link                0
comments_disabled             0
ratings_disabled              0
video_error_or_removed        0
description                 561
dtype: int64

Duplicate rows: 4263

Data types:
 video_id                               object
trending_date                  datetime64[ns]
title                                  object
channel_title                          object
category_id                            object
publish_time              datetime64[ns, UTC]
tags                                   object
views                                 float64
likes                                   int64
dislikes                                int64
comment_count                           int64
thumbnail_link                         object
comments_disabled                        bool
ratings_disabled                         bool
video_error_or_removed                   bool
description                            object
dtype: object

Sample values:
       video_id trending_date  \
0  kzwfHumJyYc           NaT
1  zUZ1z7FwLc8           NaT
2  10L1hZ9qa58           NaT
3  N1vE8iiEg64           NaT
4  kJzGH0PVQHQ           NaT

                                               title    channel_title  \
0  Sharry Mann: Cute Munda ( Song Teaser) | Parmi...  Lokdhun Punjabi
1  पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...          HJ NEWS
2  Stylish Star Allu Arjun @ ChaySam Wedding Rece...             TFPC
3                     Eruma Saani | Tamil vs English      Eruma Saani
4  why Samantha became EMOTIONAL @ Samantha naga ...       Filmylooks

  category_id              publish_time  \
0           1 2017-11-12 12:20:39+00:00
1          25 2017-11-13 05:43:56+00:00
2          24 2017-11-12 15:48:08+00:00
3          23 2017-11-12 07:08:48+00:00
4          24 2017-11-13 01:14:16+00:00

                                                tags     views  likes  \
0  sharry mann|"sharry mann new song"|"sharry man...  0.109633  33966
1  पीरियड्स के समय|"पेट पर पति करता ऐसा"|"देखकर द...  0.059010    735
2  Stylish Star Allu Arjun @ ChaySam Wedding Rece...  0.047399   2011
3  Eruma Saani|"Tamil Comedy Videos"|"Films"|"Mov...  0.124268  70353
4  Filmylooks|"latest news"|"telugu movies"|"telu...  0.046401    492

   dislikes  comment_count                                  thumbnail_link  \
0       798            882  https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg
1       904              0  https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg
2       243            149  https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg
3      1624           2684  https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg
4       293             66  https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg

   comments_disabled  ratings_disabled  video_error_or_removed  \
0              False             False                   False
1               True             False                   False
2              False             False                   False
3              False             False                   False
4              False             False                   False

                                         description
0  Presenting Sharry Mann latest Punjabi Song  Cu...
1  पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...
2  Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3  This video showcases the difference between pe...
4  why Samantha became EMOTIONAL @ Samantha naga ...

###### To check more disliked channel

In [78]:
df6=df.groupby("channel_title",as_index=False)["dislikes"].sum()

In [82]:
df6.sort_values(by="dislikes",ascending=False)

                channel_title  dislikes
1339        YouTube Spotlight   6865746
1052                 T-Series   2650896
1198            Tips Official   2370526
78               Amit Bhadana   2305446
949         Salman Khan Films   1294276
...                       ...       ...
449                    I News         0
455                 Impact TV         0
1211           Top News World         0
170            Bornali NewsBD         0
507   Kannada Bhakthi Channel         0

[1426 rows x 2 columns]